### ISSUE TITLE
TxRef Magic Code for testnet no longer X?

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon-2019#3]
to: @danpape 
cc: @mattcollier @kimdhamilton @rxgrant 

Daniel,

I thought the txref magic code for testnet would mean that it would always begin with x. How does one differentiate between mainnet and testnet now? Is this a bug in the playground txref code?

You have my testnet DID in the playground now as: 

>DID: did:btcr:8yv2-xzpq-qqqq-9yce-nk
>* TRANSACTION:
>>* TxRef: 8yv2-xzpq-qqqq-9yce-nk
>>* Block Height: 1152194
>>* Position: 0
>>* Tx Output: null
>>* TxId: f8cdaff3ebd9e862ed5885f8975489090595abe1470397f79780ead1c7528107
>>https://blockstream.info/testnet/tx/f8cdaff3ebd9e862ed5885f8975489090595abe1470397f79780ead1c7528107
>>* OP_RETURN: https://raw.githubusercontent.com/ChristopherA/self/master/ddo.jsonld
>>* Public Key Hex: 02b97c30de767f084ce3080168ee293053ba33b235d7116a3263d29f1450936b71
>>* Private Key WIF: ASK ME
>* TIP:
>>* Unspent Tip Address: mqkvMtYfTufj3iEXjYHmnopZrsowMFxrKw
>>* https://blockstream.info/testnet/address/mqkvMtYfTufj3iEXjYHmnopZrsowMFxrKw
>>* Public Key: Undisclosed
>>* Private Key WIF: ASK ME

This should eventually our canonical DID reference from things like our implicit DID Document, and ultimately our Extended DID Document.

-- Christopher Allen

**Comment by danpape** [comment]
A major change in the final BIP 136 is that there are now 4 magic codes, one for each of mainnet, testnet, mainnet with utxo bits and testnet with utxo bits. This corresponds to prefix chars of 'r', 'x', 'y', and '8', respectively. That's why your above DID starts with "did:btcr:8yv2..."

**Comment by danpape** [comment]
As discussed offline, if you want a DID that refers to the above transaction with a "short" txref (one that assumes the utxo index is 0) then you can use  did:btcr:xyv2-xzpq-q9wa-p7t
